# ==========================================
# END-TO-END 2D SED CONFIGURATION (Mel-Spectrogram -> 2D CNN)
# ==========================================

# --- 1. EXPERIMENT INFO ---
experiment:
  project_name : "birdclef2026-effnet-baseline"
  seed         : 42              
  output_dir   : "./logs/experiments"

# --- 2. DATA PIPELINE (Audio to 2D Spectrogram) ---
data:
  processed_dir   : "/kaggle/working/vigilant-octo-enigma/data/processed"
  train_split_csv : "/kaggle/working/vigilant-octo-enigma/data/fixed/train_split.csv"
  val_split_csv   : "/kaggle/working/vigilant-octo-enigma/data/fixed/val_split.csv"
  
  # taxonomy tetap mengarah ke input asli karena tidak kita ubah
  taxonomy_csv    : "/kaggle/input/competitions/birdclef-2026/taxonomy.csv"
  
  sample_rate     : 32000
  # wajib 5 detik sesuai format dataset
  max_duration    : 5.0      
  batch_size      : 32
  # disesuaikan dengan jumlah core CPU Kaggle standar
  num_workers     : 4        
  
  # parameter transformasi mel-spectrogram (feature extraction)
  n_fft           : 2048
  hop_length      : 512
  # tinggi resolusi gambar (sumbu Y)
  n_mels          : 128      
  # potong frekuensi super rendah (noise angin/gemuruh)
  fmin            : 50       
  # nyquist frequency (SR / 2)
  fmax            : 16000    

# --- 3. MODEL ARCHITECTURE (2D Vision Model) ---
model:
  model_name      : "tf_efficientnet_b0_ns"  
  pretrained      : True     
  # spektrogram adalah gambar 1 channel (grayscale)
  in_channels     : 1        
  # jumlah output node (spesies)
  num_classes     : 234      
  
  # regularization
  drop_rate       : 0.2
  drop_path_rate  : 0.2

# --- 4. TRAINING HYPERPARAMETERS ---
train:
  epochs           : 15
  learning_rate    : 1e-3     
  optimizer        : "adamw"  
  weight_decay     : 0.01    
  loss_function    : "BCEWithLogitsLoss"  
  # real batch size = 32 * 2 = 64
  gradient_accumulation_steps: 2  # berelasi dengan batch size
  
  fp16             : True
  device           : "cuda"
  logging_steps    : 50     
  save_total_limit : 2